### ISSUE TITLE
User can view the pokedex

### ISSUE THREAD

**Issue by gregg-garceau** [gregg-garceau/ajax-project#1]
## 📐 Functionality

User will be able to view a PokeDex for each generation

## ✅ Task List

- [x] Add header for the page
- [x] Add <a> tags for generations 
- [x] Create div structure for PokeDex
- [x] Create the windows inside the PokeDex
- [x] Create dots for top part of PokeDex
- [x] Create next and previous buttons on right side of pokedex
- [x] Style the colors of the PokeDex and text on the page
- [x] Make PokeDex stylistically sound on both mobile and desktop
- [x] Check for errors, remove unnecessary styling
