### ISSUE TITLE
Users can see list of Pokémon on right side

### ISSUE THREAD

**Issue by gregg-garceau** [gregg-garceau/ajax-project#2]
## 📐 Functionality

The user can see on the right side of the PokeDex a list of 20 pokemon for now

## ✅ Task List
- [x] Get data from PokeAPI for all pokemon
- [x] Loop through the data and store current pokemon
- [x] Get pokemon name and id number from results
- [x] Update text content of the list item div to show list of pokemon on right side 
- [x] Store previous and next url for going through all pokemon
- [x] Check CSS styling for both mobile and desktop
- [x] Remove unused styling and classes
