### ISSUE TITLE
User can click next and previous buttons to scroll through all Pokémon

### ISSUE THREAD

**Issue by gregg-garceau** [gregg-garceau/ajax-project#3]
## 📐 Functionality

By clicking the next and previous buttons on the right side of the PokeDex, the user is able to scroll through the list of all Pokémon

## ✅ Task List
- [x] Create event listeners for next and prev button
- [x] Create functions to change url 
- [x] Inside function call pokelist function with parameter of the stored url for next or previous
- [x] Check for errors
- [x] Check all css styling
