### ISSUE TITLE
Users can view details of specific Pokémon by clicking their name

### ISSUE THREAD

**Issue by gregg-garceau** [gregg-garceau/ajax-project#4]
## 📐 Functionality

By clicking an entry from the list of Pokémon on the right, the user is able to get data on the details for that specific Pokémon

## ✅ Task List

- [x] Add click event listeners to all list items for for right side of screen
- [x] Get the target of the click event
- [x] Get the ID of the click target
- [x] Show specific pokemon based on pokemon clicked using ID
- [x] Add on and off button for the screen
- [x] Add some styling to make buttons look good
- [x] Add click listeners to buttons to make screen add hidden class or remove hidden class
- [x] Check for errors and console logs
- [x] Check styling on mobile and desktop
