### ISSUE TITLE
Users can view Pokémon's PokeDex entry 

### ISSUE THREAD

**Issue by gregg-garceau** [gregg-garceau/ajax-project#5]
## 📐 Functionality

Collect data from PokeAPI to show on screen the stats for a pokemon 

## ✅ Task List

- [x] Grab data from a pokemon id link
- [x] Store response from api into a variable for use 
- [x] Update text content of elements using API response for name, id, height, weight and types
- [x] Update pokemon image using the API response
- [x] Change color of type text based on the color for that type
- [x] Check that it looks good on both mobile and computer screens
- [x] Check all errors and remove any console logs
